//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet.Student
{
    using System;
    using System.Collections.Generic;
    
    public partial class KUR_Otdelenie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KUR_Otdelenie()
        {
            this.KUR_Gruppa = new HashSet<KUR_Gruppa>();
            this.KUR_Suh = new HashSet<KUR_Suh>();
        }
    
        public int id_otdelenie { get; set; }
        public string naim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KUR_Gruppa> KUR_Gruppa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KUR_Suh> KUR_Suh { get; set; }
    }
}
