//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet.Student
{
    using System;
    using System.Collections.Generic;
    
    public partial class KUR_Stud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KUR_Stud()
        {
            this.KUR_Suh = new HashSet<KUR_Suh>();
        }
    
        public int id_stud { get; set; }
        public string FIO { get; set; }
        public string logi { get; set; }
        public string pass { get; set; }
        public Nullable<int> id_otdelenie { get; set; }
        public Nullable<int> id_group { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KUR_Suh> KUR_Suh { get; set; }
    }
}
