//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet.Student
{
    using System;
    using System.Collections.Generic;
    
    public partial class KUR_RASPISANIEe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KUR_RASPISANIEe()
        {
            this.KUR_Suh = new HashSet<KUR_Suh>();
        }
    
        public int id_raspisanie { get; set; }
        public int id_dnya { get; set; }
        public string Nachalo { get; set; }
        public string Para { get; set; }
        public int id_prepod { get; set; }
        public int id_predmet { get; set; }
        public string Kabinet { get; set; }
        public int id_groupp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KUR_Suh> KUR_Suh { get; set; }
    }
}
