//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet.Student
{
    using System;
    using System.Collections.Generic;
    
    public partial class KUR_Suh
    {
        public int id_suh { get; set; }
        public Nullable<int> id_stud { get; set; }
        public Nullable<int> id_prepoda { get; set; }
        public Nullable<int> id_Raspisanie { get; set; }
        public Nullable<int> id_otd { get; set; }
    
        public virtual KUR_Otdelenie KUR_Otdelenie { get; set; }
        public virtual KUR_Prep KUR_Prep { get; set; }
        public virtual KUR_RASPISANIEe KUR_RASPISANIEe { get; set; }
        public virtual KUR_Stud KUR_Stud { get; set; }
    }
}
