//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet.Student
{
    using System;
    using System.Collections.Generic;
    
    public partial class KUR_Gruppa
    {
        public int id_Gruppa { get; set; }
        public string naim { get; set; }
        public Nullable<int> id_otdel { get; set; }
    
        public virtual KUR_Otdelenie KUR_Otdelenie { get; set; }
    }
}
