//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach.Student
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user215_dbEntities2 : DbContext
    {
        public user215_dbEntities2()
            : base("name=user215_dbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KUR_Gruppa> KUR_Gruppa { get; set; }
        public virtual DbSet<KUR_Otdelenie> KUR_Otdelenie { get; set; }
        public virtual DbSet<KUR_pred> KUR_pred { get; set; }
        public virtual DbSet<KUR_Prep> KUR_Prep { get; set; }
        public virtual DbSet<KUR_RASPISANIEe> KUR_RASPISANIEe { get; set; }
        public virtual DbSet<KUR_Stud> KUR_Stud { get; set; }
        public virtual DbSet<KUR_Suh> KUR_Suh { get; set; }
    }
}
